[package]
name = "clap-autoprop"
description = "CLAP plugin exposing ChCtrlList from clap_plugin_params"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
midici-transport-clap = { path = "../../crates/midici-transport-clap" }
midici-responder = { path = "../../crates/midici-responder" }

[lints]
workspace = true
